MediCare/controlmedico/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include('core.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
]

MediCare/core/urls.py
from django.urls import path
from . import views
from .views import CreateMedico, ListMedico


app_name = 'core' 

urlpatterns = [
    # URLs para Puesto
    path('puesto/create/', views.CreatePuesto.as_view(), name='create_puesto'),
    path('puesto/list/', views.ListPuesto.as_view(), name='list_puesto'),
    path('puesto/<int:pk>/', views.DetailPuesto.as_view(), name='detail_puesto'),
    path('puesto/update/<int:pk>/', views.UpdatePuesto.as_view(), name='update_puesto'),
    path('puesto/<int:pk>/delete/', views.DeletePuesto.as_view(), name='delete_puesto'),

    # URLs para Empleado
    path('empleado/create/', views.CreateEmpleado.as_view(), name='create_empleado'),
    path('empleado/list/', views.ListEmpleado.as_view(), name='list_empleado'),
    path('empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='detail_empleado'),
    path('empleado/<int:pk>/update/', views.UpdateEmpleado.as_view(), name='update_empleado'),
    path('empleado/<int:pk>/delete/', views.DeleteEmpleado.as_view(), name='delete_empleado'),

    # URLs para Alergia
    path('alergia/create/', views.CreateAlergia.as_view(), name='create_alergia'),
    path('alergia/list/', views.ListAlergia.as_view(), name='list_alergia'),
    path('alergia/<int:pk>/', views.DetailAlergia.as_view(), name='detail_alergia'),
    path('alergia/<int:pk>/update/', views.UpdateAlergia.as_view(), name='update_alergia'),
    path('alergia/<int:pk>/delete/', views.DeleteAlergia.as_view(), name='delete_alergia'),

    # URLs para Departamento
    path('departamento/create/', views.CreateDepartamento.as_view(), name='create_departamento'),
    path('departamento/list/', views.ListDepartamento.as_view(), name='list_departamento'),
    path('departamento/<int:pk>/', views.DetailDepartamento.as_view(), name='detail_departamento'),
    path('departamento/<int:pk>/update/', views.UpdateDepartamento.as_view(), name='update_departamento'),
    path('departamento/<int:pk>/delete/', views.DeleteDepartamento.as_view(), name='delete_departamento'),

    # URLs para Medicamento
    path('medicamento/create/', views.CreateMedicamento.as_view(), name='create_medicamento'),
    path('medicamento/list/', views.ListMedicamento.as_view(), name='list_medicamento'),
    path('medicamento/<int:pk>/', views.DetailMedicamento.as_view(), name='detail_medicamento'),
    path('medicamento/<int:pk>/update/', views.UpdateMedicamento.as_view(), name='update_medicamento'),
    path('medicamento/<int:pk>/delete/', views.DeleteMedicamento.as_view(), name='delete_medicamento'),
    
    # URLs para Suministro
    path('suministro/create/', views.CreateSuministro.as_view(), name='create_suministro'),
    path('suministro/list/', views.ListSuministro.as_view(), name='list_suministro'),
    path('suministro/<int:pk>/', views.DetailSuministro.as_view(), name='detail_suministro'),
    path('suministro/<int:pk>/update/', views.UpdateSuministro.as_view(), name='update_suministro'),
    path('suministro/<int:pk>/delete/', views.DeleteSuministro.as_view(), name='delete_suministro'),

    # URLs para Medico
    path('medico/create/', views.CreateMedico.as_view(), name='create_medico'),
    path('medico/list/', views.ListMedico.as_view(), name='list_medico'),
    path('medico/<int:pk>/', views.DetailMedico.as_view(), name='detail_medico'),
    path('medico/<int:pk>/update/', views.UpdateMedico.as_view(), name='update_medico'),
    path('medico/<int:pk>/delete/', views.DeleteMedico.as_view(), name='delete_medico'),

    # URLs para Consulta
    path('consulta/create/', views.CreateConsulta.as_view(), name='create_consulta'),
    path('consulta/list/', views.ListConsulta.as_view(), name='list_consulta'),
    path('consulta/<int:pk>/', views.DetailConsulta.as_view(), name='detail_consulta'),
    path('consulta/<int:pk>/update/', views.UpdateConsulta.as_view(), name='update_consulta'),
    path('consulta/<int:pk>/delete/', views.DeleteConsulta.as_view(), name='delete_consulta'),
    
    # URLs para EfectosSecundarios
    path('efectos_secundarios/create/', views.CreateEfectosSecundarios.as_view(), name='create_efectos_secundarios'),
    path('efectos_secundarios/list/', views.ListEfectosSecundarios.as_view(), name='list_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/', views.DetailEfectosSecundarios.as_view(), name='detail_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/update/', views.UpdateEfectosSecundarios.as_view(), name='update_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/delete/', views.DeleteEfectosSecundarios.as_view(), name='delete_efectos_secundarios'),

    # URLs para Contraindicacion
    path('contraindicacion/create/', views.CreateContraindicacion.as_view(), name='create_contraindicacion'),
    path('contraindicacion/list/', views.ListContraindicacion.as_view(), name='list_contraindicacion'),
    path('contraindicacion/<int:pk>/', views.DetailContraindicacion.as_view(), name='detail_contraindicacion'),
    path('contraindicacion/<int:pk>/update/', views.UpdateContraindicacion.as_view(), name='update_contraindicacion'),
    path('contraindicacion/<int:pk>/delete/', views.DeleteContraindicacion.as_view(), name='delete_contraindicacion'),
    # URLs para FormaAdministracion
    path('forma_administracion/create/', views.CreateFormaAdministracion.as_view(), name='create_forma_administracion'),
    path('forma_administracion/list/', views.ListFormaAdministracion.as_view(), name='list_forma_administracion'),
    path('forma_administracion/<int:pk>/', views.DetailFormaAdministracion.as_view(), name='detail_forma_administracion'),
    path('forma_administracion/<int:pk>/update/', views.UpdateFormaAdministracion.as_view(), name='update_forma_administracion'),
    path('forma_administracion/<int:pk>/delete/', views.DeleteFormaAdministracion.as_view(), name='delete_forma_administracion'),

    # URLs para AlergiaEmpleado
    path('alergiaempleado/create/', views.CreateAlergiaEmpleado.as_view(), name='create_alergiaempleado'),
    path('alergiaempleado/list/', views.ListAlergiaEmpleado.as_view(), name='list_alergiaempleado'),
    path('alergiaempleado/<int:pk>/', views.DetailAlergiaEmpleado.as_view(), name='detail_alergiaempleado'),
    path('alergiaempleado/<int:pk>/update/', views.UpdateAlergiaEmpleado.as_view(), name='update_alergiaempleado'),
    path('alergiaempleado/<int:pk>/delete/', views.DeleteAlergiaEmpleado.as_view(), name='delete_alergiaempleado'),

    # URLs para MediEfecSecu
    path('medi_efec_secu/create/', views.CreateMediEfecSecu.as_view(), name='create_medi_efec_secu'),
    path('medi_efec_secu/list/', views.ListMediEfecSecu.as_view(), name='list_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/', views.DetailMediEfecSecu.as_view(), name='detail_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/update/', views.UpdateMediEfecSecu.as_view(), name='update_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/delete/', views.DeleteMediEfecSecu.as_view(), name='delete_medi_efec_secu'),

    # URLs para MediContra
    path('medi_contra/create/', views.CreateMediContra.as_view(), name='create_medi_contra'),
    path('medi_contra/list/', views.ListMediContra.as_view(), name='list_medi_contra'),
    path('medi_contra/<int:pk>/', views.DetailMediContra.as_view(), name='detail_medi_contra'),
    path('medi_contra/<int:pk>/update/', views.UpdateMediContra.as_view(), name='update_medi_contra'),
    path('medi_contra/<int:pk>/delete/', views.DeleteMediContra.as_view(), name='delete_medi_contra'),

    # URLs para MediFormaAdmi
    path('medi_forma_admi/create/', views.CreateMediFormaAdmi.as_view(), name='create_medi_forma_admi'),
    path('medi_forma_admi/list/', views.ListMediFormaAdmi.as_view(), name='list_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/', views.DetailMediFormaAdmi.as_view(), name='detail_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/update/', views.UpdateMediFormaAdmi.as_view(), name='update_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/delete/', views.DeleteMediFormaAdmi.as_view(), name='delete_medi_forma_admi'),

    # URLs para SuministroConsulta
    path('suministro_consulta/create/', views.CreateSuministroConsulta.as_view(), name='create_suministro_consulta'),
    path('suministro_consulta/list/', views.ListSuministroConsulta.as_view(), name='list_suministro_consulta'),
    path('suministro_consulta/<int:pk>/', views.DetailSuministroConsulta.as_view(), name='detail_suministro_consulta'),
    path('suministro_consulta/<int:pk>/update/', views.UpdateSuministroConsulta.as_view(), name='update_suministro_consulta'),
    path('suministro_consulta/<int:pk>/delete/', views.DeleteSuministroConsulta.as_view(), name='delete_suministro_consulta'),

    # URLs para Receta
    path('receta/create/', views.CreateReceta.as_view(), name='create_receta'),
    path('receta/list/', views.ListReceta.as_view(), name='list_receta'),
    path('receta/<int:pk>/', views.DetailReceta.as_view(), name='detail_receta'),
    path('receta/<int:pk>/update/', views.UpdateReceta.as_view(), name='update_receta'),
    path('receta/<int:pk>/delete/', views.DeleteReceta.as_view(), name='delete_receta'),

    path('receta2/list/', views.ListReceta2.as_view(), name='list_receta2'),

]

 

MediCare/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('menu', views.MenuView.as_view(), name="menu"),
    path('menuadmin', views.MenuAdminView.as_view(), name="menuadmin"),
    path('menualmacen', views.MenuAlmacenView.as_view(), name="menualmacen"),
    path('menualergias', views.MenuAlergiasView.as_view(), name="menualergias"),
    path('menuconsultas', views.MenuConsultasView.as_view(), name="menuconsultas"),
    path('menurecetas', views.MenuRecetasView.as_view(), name="menurecetas"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout'),
]

MediCare/home/models.py
from django.db import models

# Create your models here.

MediCare/home/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

MediCare/home/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LoginForm
from django.contrib import messages

class IndexView(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages  # Agrega esta línea
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LoginForm

class LoginView(generic.View):
    template_name = 'home/login.html'

    def get(self, request):
        form = LoginForm()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                if user.is_staff:
                    login(request, user)
                    return redirect('home:menuadmin')
                
                if user.is_superuser:
                    login(request, user)
                    return redirect('home:menu')
                
        context = {'form': form}
        return render(request, self.template_name, context)


def LogoutView(request):
    logout(request)
    return redirect('home:index')

class MenuView(LoginRequiredMixin, generic.View):
    template_name = "home/menu.html"
    context = {}
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

class MenuAlmacenView(LoginRequiredMixin, generic.View):
    template_name = "home/menualmacen.html"
    context = {}
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)
    
class MenuAlergiasView(LoginRequiredMixin, generic.View):
    template_name = "home/menualergias.html"
    context = {}
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)
    
class MenuConsultasView(LoginRequiredMixin, generic.View):
    template_name = "home/menuconsultas.html"
    context = {}
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)
    
class MenuRecetasView(LoginRequiredMixin, generic.View):
    template_name = "home/menurecetas.html"
    context = {}
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)
    
class MenuAdminView(LoginRequiredMixin, generic.View):
    template_name = "home/menuadmin.html"
    context = {}
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

MediCare/core/templates/home/menu.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--==title========================-->
    <title>Medi Care</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>

<section id="hero">
  <nav class="navigation">
    <!--**menu-btn*****-->
    <input type="checkbox" class="menu-btn" id="menu-btn">
    <label for="menu-btn" class="menu-icon">
        <span class="nav-icon"></span>
    </label>
    <!--**logo*********-->
    <a class="logo"><span>Medi</span>Care</a>
    <!--**menu*********-->
    <ul class="menu">
        <li><a href="{% url 'home:menu' %}">Menú</a></li>
        <li><a href="{% url 'core:list_medi_contra' %}">Contraindicaciones</a></li>
        <li><a href="{% url 'core:list_medi_efec_secu' %}">Efectos secundarios</a></li>
        <li><a href="{% url 'core:list_empleado' %}">Empleados</a></li>
        <li><a href="{% url 'core:list_medi_forma_admi' %}">Forma de administración</a></li>
    </ul>
    <a href="{% url 'home:index' %}" class="nav-appointment-btn">Cerrar sesión</a>
  </nav>
</section>

<div class="po">
  <main class="container">

    <a href="{% url 'home:menualergias' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/menualergias.png' %}">
      </div>
      <div class="product-info">
        <h2>Alergias</h2>
      </div>
    </a>

    <a href="{% url 'home:menualmacen' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/menualmacen.png' %}">
      </div>
      <div class="product-info">
        <h2>Almacén</h2>
      </div>
    </a>
   
    <a href="{% url 'home:menuconsultas' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/menuconsultas.png' %}">
      </div>
      <div class="product-info">
        <h2>Consultas</h2>
      </div>
    </a>

    <a href="{% url 'core:list_consulta' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/historialmedico.png' %}">
      </div>
      <div class="product-info">
        <h2>Historial Médico</h2>
      </div>
    </a>

    <a href="{% url 'home:menurecetas' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/recetas.png' %}">
      </div>
      <div class="product-info">
        <h2>Recetas</h2>
      </div>
    </a>
  </main>
</div>
{% endblock content %}

MediCare/core/templates/home/menuadmin.html
{ extends {}}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/menuadmin.css' %}">
    <title>Menu de Administrador</title>
</head>

<body>
  <center><h1 style="color: gold;">================== MENU ADMINISTRADOR ==================</h1></center>
  <br>
  <br>
  <br>
    <section>
    <main class="container">
        <a href="{% url 'core:list_empleado' %}" class="card card-blue">
        <div class="product-image">
            <img src="{% static 'images/ingeniero.png' %}" alt="1">
        </div>
        <div class="product-info">
            <h2>Empleados</h2>
        </div>
        </a>

        <a href="{% url 'core:list_puesto' %}" class="card card-blue">
        <div class="product-image">
            <img src="{% static 'images/puestos.png' %}" alt="2">
        </div>
        <div class="product-info">
            <h2>Puestos</h2>
        </div>
        </a>
    
        <a href="{% url 'core:list_departamento' %}" class="card card-blue">
        <div class="product-image">
            <img src="{% static 'images/empresa.png' %}" alt="3">
        </div>
        <div class="product-info">
            <h2>Departamentos</h2>
        </div>
        </a>
    </main>
  </section>
  <br>
  <br>
  <section>
    <main class="container">
        <a href="{% url 'core:list_medicamento' %}" class="card card-blue">
          <div class="product-image">
            <img src="{% static 'images/medicamentos.png' %}" alt="4">
          </div>
          <div class="product-info">
            <h2>Medicamentos</h2>
          </div>
        </a>
    
        <a href="{% url 'core:list_suministro' %}" class="card card-blue">
          <div class="product-image">
            <img src="{% static 'images/suministros.png' %}" alt="5">
          </div>
          <div class="product-info">
            <h2>Suministros</h2>
          </div>
        </a>
    
        <a href="{% url 'core:list_medico' %}" class="card card-blue">
          <div class="product-image">
            <img src="{% static 'images/doctor.png' %}" alt="5">
          </div>
          <div class="product-info">
            <h2>Medicos</h2>
          </div>
        </a>
      </main>
  </section>
  <br>
  <br>
</body>
</html>

MediCare/core/templates/home/menualergias.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--==title========================-->
    <title>Medi Care</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>

<section id="hero">
  <nav class="navigation">
    <input type="checkbox" class="menu-btn" id="menu-btn">
    <label for="menu-btn" class="menu-icon">
        <span class="nav-icon"></span>
    </label>
    <!--**logo*********-->
    <a class="logo"><span>Medi</span>Care</a>
    <!--**menu*********-->
    <ul class="menu">
        <li><a href="{% url 'home:menu' %}">Menú</a></li>
        <li><a href="{% url 'core:list_medi_contra' %}">Contraindicaciones</a></li>
        <li><a href="{% url 'core:list_medi_efec_secu' %}">Efectos secundarios</a></li>
        <li><a href="{% url 'core:list_empleado' %}">Empleados</a></li>
        <li><a href="{% url 'core:list_forma_administracion' %}">Forma de administración</a></li>
    </ul>
    <a href="{% url 'home:index' %}" class="nav-appointment-btn">Cerrar sesión</a>
  </nav>
</section>
  <main class="container">

    <a href="{% url 'home:menu' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/puerta.png' %}">
      </div>
      <div class="product-info">
        <h2>Volver</h2>
      </div>
    </a>

    <a href="{% url 'core:list_alergia' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/lista-alergias.png' %}">
      </div>
      <div class="product-info">
        <h2>Lista de Alergias</h2>
      </div>
    </a>

    <a href="{% url 'core:list_alergiaempleado' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/alergias-empleados.png' %}">
      </div>
      <div class="product-info">
        <h2>Alergias-Empleados</h2>
      </div>
    </a>

  </main>
{% endblock content %}

MediCare/core/templates/home/menualmacen.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--==title========================-->
    <title>Medi Care</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>
<body>
<section id="hero">
  <nav class="navigation">
    <!--**menu-btn*****-->
    <input type="checkbox" class="menu-btn" id="menu-btn">
    <label for="menu-btn" class="menu-icon">
        <span class="nav-icon"></span>
    </label>
    <!--**logo*********-->
    <a class="logo"><span>Medi</span>Care</a>
    <!--**menu*********-->
    <ul class="menu">
        <li><a href="{% url 'home:menu' %}">Menú</a></li>
        <li><a href="{% url 'core:list_medi_contra' %}">Contraindicaciones</a></li>
        <li><a href="{% url 'core:list_medi_efec_secu' %}">Efectos secundarios</a></li>
        <li><a href="{% url 'core:list_empleado' %}">Empleados</a></li>
        <li><a href="{% url 'core:list_forma_administracion' %}">Forma de administración</a></li>
    </ul>
    <a href="{% url 'home:index' %}" class="nav-appointment-btn">Cerrar sesión</a>
  </nav>
</section>
  <main class="container">

    <a href="{% url 'home:menu' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/puerta.png' %}">
      </div>
      <div class="product-info">
        <h2>Volver</h2>
      </div>
    </a>

    <a href="{% url 'core:list_medicamento' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/medicamentos.png' %}">
      </div>
      <div class="product-info">
        <h2>Medicamentos</h2>
      </div>
    </a>

    <a href="{% url 'core:list_suministro' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/suministros.png' %}">
      </div>
      <div class="product-info">
        <h2>Suministros</h2>
      </div>
    </a>

  </main>
</body>
{% endblock content %}

MediCare/core/templates/home/menuconsultas.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--==title========================-->
    <title>Medi Care</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>

<section id="hero">
  <nav class="navigation">
    <!--**menu-btn*****-->
    <input type="checkbox" class="menu-btn" id="menu-btn">
    <label for="menu-btn" class="menu-icon">
        <span class="nav-icon"></span>
    </label>
    <!--**logo*********-->
    <a class="logo"><span>Medi</span>Care</a>
    <!--**menu*********-->
    <ul class="menu">
        <li><a href="{% url 'home:menu' %}">Menú</a></li>
        <li><a href="{% url 'core:list_medi_contra' %}">Contraindicaciones</a></li>
        <li><a href="{% url 'core:list_medi_efec_secu' %}">Efectos secundarios</a></li>
        <li><a href="{% url 'core:list_empleado' %}">Empleados</a></li>
        <li><a href="{% url 'core:list_forma_administracion' %}">Forma de administración</a></li>
    </ul>
    <a href="{% url 'home:index' %}" class="nav-appointment-btn">Cerrar sesión</a>
  </nav>
</section>
  <main class="container">

    <a href="{% url 'home:menu' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/puerta.png' %}">
      </div>
      <div class="product-info">
        <h2>Volver</h2>
      </div>
    </a>

    <a href="{% url 'core:create_consulta' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/menuconsultas.png' %}">
      </div>
      <div class="product-info">
        <h2>Crear consulta</h2>
      </div>
    </a>

    <a href="{% url 'core:list_receta' %}" class="card card-blue">
      <div class="product-image">
        <img src="{% static 'images/consulta-medicamento.png' %}">
      </div>
      <div class="product-info">
        <h2>Consulta-Medicamento</h2>
      </div>
    </a>

    <a href="{% url 'core:list_suministro_consulta' %}" class="card card-blue">
        <div class="product-image">
          <img src="{% static 'images/suministros.png' %}" alt="1">
        </div>
        <div class="product-info">
          <h2>Consulta-Suministro</h2>
        </div>
      </a>

  </main>
</body>
{% endblock content %}