MediCare/controlmedico/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include('core.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
]

MediCare/core/urls.py
from django.urls import path
from . import views
from .views import CreateMedico, ListMedico


app_name = 'core' 

urlpatterns = [
    # URLs para Puesto
    path('puesto/create/', views.CreatePuesto.as_view(), name='create_puesto'),
    path('puesto/list/', views.ListPuesto.as_view(), name='list_puesto'),
    path('puesto/<int:pk>/', views.DetailPuesto.as_view(), name='detail_puesto'),
    path('puesto/update/<int:pk>/', views.UpdatePuesto.as_view(), name='update_puesto'),
    path('puesto/<int:pk>/delete/', views.DeletePuesto.as_view(), name='delete_puesto'),

    # URLs para Empleado
    path('empleado/create/', views.CreateEmpleado.as_view(), name='create_empleado'),
    path('empleado/list/', views.ListEmpleado.as_view(), name='list_empleado'),
    path('empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='detail_empleado'),
    path('empleado/<int:pk>/update/', views.UpdateEmpleado.as_view(), name='update_empleado'),
    path('empleado/<int:pk>/delete/', views.DeleteEmpleado.as_view(), name='delete_empleado'),

    # URLs para Alergia
    path('alergia/create/', views.CreateAlergia.as_view(), name='create_alergia'),
    path('alergia/list/', views.ListAlergia.as_view(), name='list_alergia'),
    path('alergia/<int:pk>/', views.DetailAlergia.as_view(), name='detail_alergia'),
    path('alergia/<int:pk>/update/', views.UpdateAlergia.as_view(), name='update_alergia'),
    path('alergia/<int:pk>/delete/', views.DeleteAlergia.as_view(), name='delete_alergia'),

    # URLs para Departamento
    path('departamento/create/', views.CreateDepartamento.as_view(), name='create_departamento'),
    path('departamento/list/', views.ListDepartamento.as_view(), name='list_departamento'),
    path('departamento/<int:pk>/', views.DetailDepartamento.as_view(), name='detail_departamento'),
    path('departamento/<int:pk>/update/', views.UpdateDepartamento.as_view(), name='update_departamento'),
    path('departamento/<int:pk>/delete/', views.DeleteDepartamento.as_view(), name='delete_departamento'),

    # URLs para Medicamento
    path('medicamento/create/', views.CreateMedicamento.as_view(), name='create_medicamento'),
    path('medicamento/list/', views.ListMedicamento.as_view(), name='list_medicamento'),
    path('medicamento/<int:pk>/', views.DetailMedicamento.as_view(), name='detail_medicamento'),
    path('medicamento/<int:pk>/update/', views.UpdateMedicamento.as_view(), name='update_medicamento'),
    path('medicamento/<int:pk>/delete/', views.DeleteMedicamento.as_view(), name='delete_medicamento'),
    
    # URLs para Suministro
    path('suministro/create/', views.CreateSuministro.as_view(), name='create_suministro'),
    path('suministro/list/', views.ListSuministro.as_view(), name='list_suministro'),
    path('suministro/<int:pk>/', views.DetailSuministro.as_view(), name='detail_suministro'),
    path('suministro/<int:pk>/update/', views.UpdateSuministro.as_view(), name='update_suministro'),
    path('suministro/<int:pk>/delete/', views.DeleteSuministro.as_view(), name='delete_suministro'),

    # URLs para Medico
    path('medico/create/', views.CreateMedico.as_view(), name='create_medico'),
    path('medico/list/', views.ListMedico.as_view(), name='list_medico'),
    path('medico/<int:pk>/', views.DetailMedico.as_view(), name='detail_medico'),
    path('medico/<int:pk>/update/', views.UpdateMedico.as_view(), name='update_medico'),
    path('medico/<int:pk>/delete/', views.DeleteMedico.as_view(), name='delete_medico'),

    # URLs para Consulta
    path('consulta/create/', views.CreateConsulta.as_view(), name='create_consulta'),
    path('consulta/list/', views.ListConsulta.as_view(), name='list_consulta'),
    path('consulta/<int:pk>/', views.DetailConsulta.as_view(), name='detail_consulta'),
    path('consulta/<int:pk>/update/', views.UpdateConsulta.as_view(), name='update_consulta'),
    path('consulta/<int:pk>/delete/', views.DeleteConsulta.as_view(), name='delete_consulta'),
    
    # URLs para EfectosSecundarios
    path('efectos_secundarios/create/', views.CreateEfectosSecundarios.as_view(), name='create_efectos_secundarios'),
    path('efectos_secundarios/list/', views.ListEfectosSecundarios.as_view(), name='list_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/', views.DetailEfectosSecundarios.as_view(), name='detail_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/update/', views.UpdateEfectosSecundarios.as_view(), name='update_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/delete/', views.DeleteEfectosSecundarios.as_view(), name='delete_efectos_secundarios'),

    # URLs para Contraindicacion
    path('contraindicacion/create/', views.CreateContraindicacion.as_view(), name='create_contraindicacion'),
    path('contraindicacion/list/', views.ListContraindicacion.as_view(), name='list_contraindicacion'),
    path('contraindicacion/<int:pk>/', views.DetailContraindicacion.as_view(), name='detail_contraindicacion'),
    path('contraindicacion/<int:pk>/update/', views.UpdateContraindicacion.as_view(), name='update_contraindicacion'),
    path('contraindicacion/<int:pk>/delete/', views.DeleteContraindicacion.as_view(), name='delete_contraindicacion'),
    # URLs para FormaAdministracion
    path('forma_administracion/create/', views.CreateFormaAdministracion.as_view(), name='create_forma_administracion'),
    path('forma_administracion/list/', views.ListFormaAdministracion.as_view(), name='list_forma_administracion'),
    path('forma_administracion/<int:pk>/', views.DetailFormaAdministracion.as_view(), name='detail_forma_administracion'),
    path('forma_administracion/<int:pk>/update/', views.UpdateFormaAdministracion.as_view(), name='update_forma_administracion'),
    path('forma_administracion/<int:pk>/delete/', views.DeleteFormaAdministracion.as_view(), name='delete_forma_administracion'),

    # URLs para AlergiaEmpleado
    path('alergiaempleado/create/', views.CreateAlergiaEmpleado.as_view(), name='create_alergiaempleado'),
    path('alergiaempleado/list/', views.ListAlergiaEmpleado.as_view(), name='list_alergiaempleado'),
    path('alergiaempleado/<int:pk>/', views.DetailAlergiaEmpleado.as_view(), name='detail_alergiaempleado'),
    path('alergiaempleado/<int:pk>/update/', views.UpdateAlergiaEmpleado.as_view(), name='update_alergiaempleado'),
    path('alergiaempleado/<int:pk>/delete/', views.DeleteAlergiaEmpleado.as_view(), name='delete_alergiaempleado'),

    # URLs para MediEfecSecu
    path('medi_efec_secu/create/', views.CreateMediEfecSecu.as_view(), name='create_medi_efec_secu'),
    path('medi_efec_secu/list/', views.ListMediEfecSecu.as_view(), name='list_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/', views.DetailMediEfecSecu.as_view(), name='detail_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/update/', views.UpdateMediEfecSecu.as_view(), name='update_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/delete/', views.DeleteMediEfecSecu.as_view(), name='delete_medi_efec_secu'),

    # URLs para MediContra
    path('medi_contra/create/', views.CreateMediContra.as_view(), name='create_medi_contra'),
    path('medi_contra/list/', views.ListMediContra.as_view(), name='list_medi_contra'),
    path('medi_contra/<int:pk>/', views.DetailMediContra.as_view(), name='detail_medi_contra'),
    path('medi_contra/<int:pk>/update/', views.UpdateMediContra.as_view(), name='update_medi_contra'),
    path('medi_contra/<int:pk>/delete/', views.DeleteMediContra.as_view(), name='delete_medi_contra'),

    # URLs para MediFormaAdmi
    path('medi_forma_admi/create/', views.CreateMediFormaAdmi.as_view(), name='create_medi_forma_admi'),
    path('medi_forma_admi/list/', views.ListMediFormaAdmi.as_view(), name='list_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/', views.DetailMediFormaAdmi.as_view(), name='detail_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/update/', views.UpdateMediFormaAdmi.as_view(), name='update_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/delete/', views.DeleteMediFormaAdmi.as_view(), name='delete_medi_forma_admi'),

    # URLs para SuministroConsulta
    path('suministro_consulta/create/', views.CreateSuministroConsulta.as_view(), name='create_suministro_consulta'),
    path('suministro_consulta/list/', views.ListSuministroConsulta.as_view(), name='list_suministro_consulta'),
    path('suministro_consulta/<int:pk>/', views.DetailSuministroConsulta.as_view(), name='detail_suministro_consulta'),
    path('suministro_consulta/<int:pk>/update/', views.UpdateSuministroConsulta.as_view(), name='update_suministro_consulta'),
    path('suministro_consulta/<int:pk>/delete/', views.DeleteSuministroConsulta.as_view(), name='delete_suministro_consulta'),

    # URLs para Receta
    path('receta/create/', views.CreateReceta.as_view(), name='create_receta'),
    path('receta/list/', views.ListReceta.as_view(), name='list_receta'),
    path('receta/<int:pk>/', views.DetailReceta.as_view(), name='detail_receta'),
    path('receta/<int:pk>/update/', views.UpdateReceta.as_view(), name='update_receta'),
    path('receta/<int:pk>/delete/', views.DeleteReceta.as_view(), name='delete_receta'),

    path('receta2/list/', views.ListReceta2.as_view(), name='list_receta2'),

]

 

MediCare/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('menu', views.MenuView.as_view(), name="menu"),
    path('menuadmin', views.MenuAdminView.as_view(), name="menuadmin"),
    path('menualmacen', views.MenuAlmacenView.as_view(), name="menualmacen"),
    path('menualergias', views.MenuAlergiasView.as_view(), name="menualergias"),
    path('menuconsultas', views.MenuConsultasView.as_view(), name="menuconsultas"),
    path('menurecetas', views.MenuRecetasView.as_view(), name="menurecetas"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout'),
]

MediCare/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta


# Create your models here.

class Alergia(models.Model):
    nombre = models.CharField(max_length=100, null=True)
    descripcion = models.TextField(max_length=255, null=True)

    def __str__(self):
        return self.nombre

class Puesto(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=50, null=True)

    def __str__(self):
        return self.nombre

class Departamento(models.Model):
    nombre = models.CharField(max_length=50, null=True)
    descripcion = models.TextField(max_length=70, null=True)

    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    nombrePila = models.CharField(max_length=20, null=True)
    apPat = models.CharField(max_length=20, null=True)
    apMat = models.CharField(max_length=20, null=True)
    fnacimiento = models.DateField()
    noempleado = models.CharField(max_length=10, null=True)
    puesto = models.ForeignKey('Puesto', on_delete=models.CASCADE)
    departamento = models.ForeignKey('Departamento', on_delete=models.CASCADE, default='')

    alergias = models.ManyToManyField('Alergia', through='AlergiaEmpleado')

    def __str__(self):
        return f"{self.noempleado} {self.nombrePila} {self.apPat} {self.apMat} "

class Medicamento(models.Model):
    nombre = models.CharField(max_length=40)
    descripcion = models.TextField(max_length=40)
    dosis = models.IntegerField()
    stock = models.IntegerField()

    efectos_secundarios = models.ManyToManyField('EfectosSecundarios', through='MediEfecSecu')
    contraindicaciones = models.ManyToManyField('Contraindicacion', through='MediContra')
    formas_administracion = models.ManyToManyField('FormaAdministracion', through='MediFormaAdmi')

    def __str__(self):
        return self.nombre

class Suministro(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=50)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre

class Medico(models.Model):
    nombrePila = models.CharField(max_length=20)
    apPat = models.CharField(max_length=20, null=True)
    apMat = models.CharField(max_length=20, null=True)
    cedula = models.CharField(max_length=10, null=True)
    numTel = models.BigIntegerField()

    def __str__(self):
        return self.nombrePila

class Consulta(models.Model):
    fecha = models.DateField()
    edad = models.IntegerField()
    motivo = models.CharField(max_length=255, null=True)
    sintomas = models.CharField(max_length=255, null=True)
    peso = models.DecimalField(max_digits=5, decimal_places=2)
    altura = models.DecimalField(max_digits=5, decimal_places=2)
    diagnostico = models.CharField(max_length=255, null=True)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)
    medico = models.ForeignKey('Medico', on_delete=models.CASCADE)

    medicamentos = models.ManyToManyField('Medicamento', through='Receta')
    suministros = models.ManyToManyField('Suministro', through='SuministroConsulta')

    def __str__(self):
        return str(self.id)

class EfectosSecundarios(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class Contraindicacion(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class FormaAdministracion(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class AlergiaEmpleado(models.Model):
    alergia = models.ForeignKey('Alergia', on_delete=models.CASCADE)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.alergia)

class SuministroConsulta(models.Model):
    suministro = models.ForeignKey('Suministro', on_delete=models.CASCADE)
    consulta = models.ForeignKey('Consulta', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default='1')

    def __str__(self):
        return f"{self.suministro} - {self.consulta}"

class Receta(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    consulta = models.ForeignKey('Consulta', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default='1')
    dosis = models.CharField(max_length=255, null=True)
    duracion = models.CharField(max_length=255, null=True)
    
    def __str__(self):
        fecha_consulta = self.consulta.fecha
        nombrePila_empleado = self.consulta.empleado.nombrePila
        nombreapPat_empleado = self.consulta.empleado.apPat
        nombreapMat_empleado = self.consulta.empleado.apMat
        return f"{self.medicamento} - Consulta el {fecha_consulta} con {nombrePila_empleado} {nombreapPat_empleado} {nombreapMat_empleado}"

    
class MediEfecSecu(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    efectosSecundarios = models.ForeignKey('EfectosSecundarios', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

class MediContra(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    contraindicaciones = models.ForeignKey('Contraindicacion', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

class MediFormaAdmi(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    formaAdministracion = models.ForeignKey('FormaAdministracion', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

MediCare/core/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--==title========================-->
    <title>Medi Care</title>
    <!--==Fav-icon=====================-->
    <link rel="shortcut icon" href="{% static 'images/fav-icon.png' }%">
    <!--==CSS==========================-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!--==Font-Awesome-for-icons=====-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
</head>
<body>
    <div class="row">
        <div class="col-8">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</body>
</html>

MediCare/core/templates/base/receta.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="{% static 'images/fav-icon.png' %}">
    <!--==CSS==========================-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            color: #495057;
        }

        .container {
            width: 450px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            margin-top: 30px;
        }

        h3 {
            color: #007bff;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        table,
        th,
        td {
            border: 1px solid #dee2e6;
        }

        th,
        td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #007bff;
            color: #ffffff;
        }

        a {
            text-decoration: none;
            color: #007bff;
            font-weight: bold;
        }

        a:hover {
            color: #0056b3;
        }

        .btn-secondary {
            background-color: #6c757d;
            color: #ffffff;
            padding: 8px 15px;
            text-decoration: none;
            border-radius: 3px;
        }
    </style>
</head>

<body>
    <section id="hero">
        <nav class="navigation">
            <!--**menu-btn*****-->
            <input type="checkbox" class="menu-btn" id="menu-btn">
            <label for="menu-btn" class="menu-icon">
                <span class="nav-icon"></span>
            </label>
            <!--**logo*********-->
            <a class="logo"><span>Medi</span>Care</a>
            <!--**menu*********-->
            <ul class="menu">
                <li><a href="{% url 'home:menu' %}">Menú</a></li>
                <li><a href="{% url 'core:list_medi_contra' %}">Contraindicaciones</a></li>
                <li><a href="{% url 'core:list_medi_efec_secu' %}">Efectos secundarios</a></li>
                <li><a href="{% url 'core:list_empleado' %}">Empleados</a></li>
                <li><a href="{% url 'core:list_medi_forma_admi' %}">Forma de administración</a></li>
            </ul>
            <a href="{% url 'home:index' %}" class="nav-appointment-btn">Cerrar sesión</a>
        </nav><!--nav-end-->
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
    </section>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

MediCare/core/templates/base/tablas.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="{% static 'images/fav-icon.png' }%">
    <!--==CSS==========================-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <section id="hero">
        <nav class="navigation">
          <!--**menu-btn*****-->
          <input type="checkbox" class="menu-btn" id="menu-btn">
          <label for="menu-btn" class="menu-icon">
              <span class="nav-icon"></span>
          </label>
          <!--**logo*********-->
          <a class="logo"><span>Medi</span>Care</a>
          <!--**menu*********-->
          <ul class="menu">
              <li><a href="{% url 'home:menu' %}">Menú</a></li>
              <li><a href="{% url 'core:list_medi_contra' %}">Contraindicaciones</a></li>
              <li><a href="{% url 'core:list_medi_efec_secu' %}">Efectos secundarios</a></li>
              <li><a href="{% url 'core:list_empleado' %}">Empleados</a></li>
              <li><a href="{% url 'core:list_medi_forma_admi' %}">Forma de administración</a></li>
          </ul>
          <a href="{% url 'home:index' %}" class="nav-appointment-btn">Cerrar sesión</a>
        </nav><!--nav-end-->
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
    </section>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>