MediCare/controlmedico/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include('core.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
]

MediCare/core/urls.py
from django.urls import path
from . import views
from .views import CreateMedico, ListMedico


app_name = 'core' 

urlpatterns = [
    # URLs para Puesto
    path('puesto/create/', views.CreatePuesto.as_view(), name='create_puesto'),
    path('puesto/list/', views.ListPuesto.as_view(), name='list_puesto'),
    path('puesto/<int:pk>/', views.DetailPuesto.as_view(), name='detail_puesto'),
    path('puesto/update/<int:pk>/', views.UpdatePuesto.as_view(), name='update_puesto'),
    path('puesto/<int:pk>/delete/', views.DeletePuesto.as_view(), name='delete_puesto'),

    # URLs para Empleado
    path('empleado/create/', views.CreateEmpleado.as_view(), name='create_empleado'),
    path('empleado/list/', views.ListEmpleado.as_view(), name='list_empleado'),
    path('empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='detail_empleado'),
    path('empleado/<int:pk>/update/', views.UpdateEmpleado.as_view(), name='update_empleado'),
    path('empleado/<int:pk>/delete/', views.DeleteEmpleado.as_view(), name='delete_empleado'),

    # URLs para Alergia
    path('alergia/create/', views.CreateAlergia.as_view(), name='create_alergia'),
    path('alergia/list/', views.ListAlergia.as_view(), name='list_alergia'),
    path('alergia/<int:pk>/', views.DetailAlergia.as_view(), name='detail_alergia'),
    path('alergia/<int:pk>/update/', views.UpdateAlergia.as_view(), name='update_alergia'),
    path('alergia/<int:pk>/delete/', views.DeleteAlergia.as_view(), name='delete_alergia'),

    # URLs para Departamento
    path('departamento/create/', views.CreateDepartamento.as_view(), name='create_departamento'),
    path('departamento/list/', views.ListDepartamento.as_view(), name='list_departamento'),
    path('departamento/<int:pk>/', views.DetailDepartamento.as_view(), name='detail_departamento'),
    path('departamento/<int:pk>/update/', views.UpdateDepartamento.as_view(), name='update_departamento'),
    path('departamento/<int:pk>/delete/', views.DeleteDepartamento.as_view(), name='delete_departamento'),

    # URLs para Medicamento
    path('medicamento/create/', views.CreateMedicamento.as_view(), name='create_medicamento'),
    path('medicamento/list/', views.ListMedicamento.as_view(), name='list_medicamento'),
    path('medicamento/<int:pk>/', views.DetailMedicamento.as_view(), name='detail_medicamento'),
    path('medicamento/<int:pk>/update/', views.UpdateMedicamento.as_view(), name='update_medicamento'),
    path('medicamento/<int:pk>/delete/', views.DeleteMedicamento.as_view(), name='delete_medicamento'),
    
    # URLs para Suministro
    path('suministro/create/', views.CreateSuministro.as_view(), name='create_suministro'),
    path('suministro/list/', views.ListSuministro.as_view(), name='list_suministro'),
    path('suministro/<int:pk>/', views.DetailSuministro.as_view(), name='detail_suministro'),
    path('suministro/<int:pk>/update/', views.UpdateSuministro.as_view(), name='update_suministro'),
    path('suministro/<int:pk>/delete/', views.DeleteSuministro.as_view(), name='delete_suministro'),

    # URLs para Medico
    path('medico/create/', views.CreateMedico.as_view(), name='create_medico'),
    path('medico/list/', views.ListMedico.as_view(), name='list_medico'),
    path('medico/<int:pk>/', views.DetailMedico.as_view(), name='detail_medico'),
    path('medico/<int:pk>/update/', views.UpdateMedico.as_view(), name='update_medico'),
    path('medico/<int:pk>/delete/', views.DeleteMedico.as_view(), name='delete_medico'),

    # URLs para Consulta
    path('consulta/create/', views.CreateConsulta.as_view(), name='create_consulta'),
    path('consulta/list/', views.ListConsulta.as_view(), name='list_consulta'),
    path('consulta/<int:pk>/', views.DetailConsulta.as_view(), name='detail_consulta'),
    path('consulta/<int:pk>/update/', views.UpdateConsulta.as_view(), name='update_consulta'),
    path('consulta/<int:pk>/delete/', views.DeleteConsulta.as_view(), name='delete_consulta'),
    
    # URLs para EfectosSecundarios
    path('efectos_secundarios/create/', views.CreateEfectosSecundarios.as_view(), name='create_efectos_secundarios'),
    path('efectos_secundarios/list/', views.ListEfectosSecundarios.as_view(), name='list_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/', views.DetailEfectosSecundarios.as_view(), name='detail_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/update/', views.UpdateEfectosSecundarios.as_view(), name='update_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/delete/', views.DeleteEfectosSecundarios.as_view(), name='delete_efectos_secundarios'),

    # URLs para Contraindicacion
    path('contraindicacion/create/', views.CreateContraindicacion.as_view(), name='create_contraindicacion'),
    path('contraindicacion/list/', views.ListContraindicacion.as_view(), name='list_contraindicacion'),
    path('contraindicacion/<int:pk>/', views.DetailContraindicacion.as_view(), name='detail_contraindicacion'),
    path('contraindicacion/<int:pk>/update/', views.UpdateContraindicacion.as_view(), name='update_contraindicacion'),
    path('contraindicacion/<int:pk>/delete/', views.DeleteContraindicacion.as_view(), name='delete_contraindicacion'),
    # URLs para FormaAdministracion
    path('forma_administracion/create/', views.CreateFormaAdministracion.as_view(), name='create_forma_administracion'),
    path('forma_administracion/list/', views.ListFormaAdministracion.as_view(), name='list_forma_administracion'),
    path('forma_administracion/<int:pk>/', views.DetailFormaAdministracion.as_view(), name='detail_forma_administracion'),
    path('forma_administracion/<int:pk>/update/', views.UpdateFormaAdministracion.as_view(), name='update_forma_administracion'),
    path('forma_administracion/<int:pk>/delete/', views.DeleteFormaAdministracion.as_view(), name='delete_forma_administracion'),

    # URLs para AlergiaEmpleado
    path('alergiaempleado/create/', views.CreateAlergiaEmpleado.as_view(), name='create_alergiaempleado'),
    path('alergiaempleado/list/', views.ListAlergiaEmpleado.as_view(), name='list_alergiaempleado'),
    path('alergiaempleado/<int:pk>/', views.DetailAlergiaEmpleado.as_view(), name='detail_alergiaempleado'),
    path('alergiaempleado/<int:pk>/update/', views.UpdateAlergiaEmpleado.as_view(), name='update_alergiaempleado'),
    path('alergiaempleado/<int:pk>/delete/', views.DeleteAlergiaEmpleado.as_view(), name='delete_alergiaempleado'),

    # URLs para MediEfecSecu
    path('medi_efec_secu/create/', views.CreateMediEfecSecu.as_view(), name='create_medi_efec_secu'),
    path('medi_efec_secu/list/', views.ListMediEfecSecu.as_view(), name='list_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/', views.DetailMediEfecSecu.as_view(), name='detail_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/update/', views.UpdateMediEfecSecu.as_view(), name='update_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/delete/', views.DeleteMediEfecSecu.as_view(), name='delete_medi_efec_secu'),

    # URLs para MediContra
    path('medi_contra/create/', views.CreateMediContra.as_view(), name='create_medi_contra'),
    path('medi_contra/list/', views.ListMediContra.as_view(), name='list_medi_contra'),
    path('medi_contra/<int:pk>/', views.DetailMediContra.as_view(), name='detail_medi_contra'),
    path('medi_contra/<int:pk>/update/', views.UpdateMediContra.as_view(), name='update_medi_contra'),
    path('medi_contra/<int:pk>/delete/', views.DeleteMediContra.as_view(), name='delete_medi_contra'),

    # URLs para MediFormaAdmi
    path('medi_forma_admi/create/', views.CreateMediFormaAdmi.as_view(), name='create_medi_forma_admi'),
    path('medi_forma_admi/list/', views.ListMediFormaAdmi.as_view(), name='list_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/', views.DetailMediFormaAdmi.as_view(), name='detail_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/update/', views.UpdateMediFormaAdmi.as_view(), name='update_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/delete/', views.DeleteMediFormaAdmi.as_view(), name='delete_medi_forma_admi'),

    # URLs para SuministroConsulta
    path('suministro_consulta/create/', views.CreateSuministroConsulta.as_view(), name='create_suministro_consulta'),
    path('suministro_consulta/list/', views.ListSuministroConsulta.as_view(), name='list_suministro_consulta'),
    path('suministro_consulta/<int:pk>/', views.DetailSuministroConsulta.as_view(), name='detail_suministro_consulta'),
    path('suministro_consulta/<int:pk>/update/', views.UpdateSuministroConsulta.as_view(), name='update_suministro_consulta'),
    path('suministro_consulta/<int:pk>/delete/', views.DeleteSuministroConsulta.as_view(), name='delete_suministro_consulta'),

    # URLs para Receta
    path('receta/create/', views.CreateReceta.as_view(), name='create_receta'),
    path('receta/list/', views.ListReceta.as_view(), name='list_receta'),
    path('receta/<int:pk>/', views.DetailReceta.as_view(), name='detail_receta'),
    path('receta/<int:pk>/update/', views.UpdateReceta.as_view(), name='update_receta'),
    path('receta/<int:pk>/delete/', views.DeleteReceta.as_view(), name='delete_receta'),

    path('receta2/list/', views.ListReceta2.as_view(), name='list_receta2'),

]

 

MediCare/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('menu', views.MenuView.as_view(), name="menu"),
    path('menuadmin', views.MenuAdminView.as_view(), name="menuadmin"),
    path('menualmacen', views.MenuAlmacenView.as_view(), name="menualmacen"),
    path('menualergias', views.MenuAlergiasView.as_view(), name="menualergias"),
    path('menuconsultas', views.MenuConsultasView.as_view(), name="menuconsultas"),
    path('menurecetas', views.MenuRecetasView.as_view(), name="menurecetas"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout'),
]

MediCare/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta


# Create your models here.

class Alergia(models.Model):
    nombre = models.CharField(max_length=100, null=True)
    descripcion = models.TextField(max_length=255, null=True)

    def __str__(self):
        return self.nombre

class Puesto(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=50, null=True)

    def __str__(self):
        return self.nombre

class Departamento(models.Model):
    nombre = models.CharField(max_length=50, null=True)
    descripcion = models.TextField(max_length=70, null=True)

    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    nombrePila = models.CharField(max_length=20, null=True)
    apPat = models.CharField(max_length=20, null=True)
    apMat = models.CharField(max_length=20, null=True)
    fnacimiento = models.DateField()
    noempleado = models.CharField(max_length=10, null=True)
    puesto = models.ForeignKey('Puesto', on_delete=models.CASCADE)
    departamento = models.ForeignKey('Departamento', on_delete=models.CASCADE, default='')

    alergias = models.ManyToManyField('Alergia', through='AlergiaEmpleado')

    def __str__(self):
        return f"{self.noempleado} {self.nombrePila} {self.apPat} {self.apMat} "

class Medicamento(models.Model):
    nombre = models.CharField(max_length=40)
    descripcion = models.TextField(max_length=40)
    dosis = models.IntegerField()
    stock = models.IntegerField()

    efectos_secundarios = models.ManyToManyField('EfectosSecundarios', through='MediEfecSecu')
    contraindicaciones = models.ManyToManyField('Contraindicacion', through='MediContra')
    formas_administracion = models.ManyToManyField('FormaAdministracion', through='MediFormaAdmi')

    def __str__(self):
        return self.nombre

class Suministro(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=50)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre

class Medico(models.Model):
    nombrePila = models.CharField(max_length=20)
    apPat = models.CharField(max_length=20, null=True)
    apMat = models.CharField(max_length=20, null=True)
    cedula = models.CharField(max_length=10, null=True)
    numTel = models.BigIntegerField()

    def __str__(self):
        return self.nombrePila

class Consulta(models.Model):
    fecha = models.DateField()
    edad = models.IntegerField()
    motivo = models.CharField(max_length=255, null=True)
    sintomas = models.CharField(max_length=255, null=True)
    peso = models.DecimalField(max_digits=5, decimal_places=2)
    altura = models.DecimalField(max_digits=5, decimal_places=2)
    diagnostico = models.CharField(max_length=255, null=True)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)
    medico = models.ForeignKey('Medico', on_delete=models.CASCADE)

    medicamentos = models.ManyToManyField('Medicamento', through='Receta')
    suministros = models.ManyToManyField('Suministro', through='SuministroConsulta')

    def __str__(self):
        return str(self.id)

class EfectosSecundarios(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class Contraindicacion(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class FormaAdministracion(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class AlergiaEmpleado(models.Model):
    alergia = models.ForeignKey('Alergia', on_delete=models.CASCADE)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.alergia)

class SuministroConsulta(models.Model):
    suministro = models.ForeignKey('Suministro', on_delete=models.CASCADE)
    consulta = models.ForeignKey('Consulta', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default='1')

    def __str__(self):
        return f"{self.suministro} - {self.consulta}"

class Receta(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    consulta = models.ForeignKey('Consulta', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default='1')
    dosis = models.CharField(max_length=255, null=True)
    duracion = models.CharField(max_length=255, null=True)
    
    def __str__(self):
        fecha_consulta = self.consulta.fecha
        nombrePila_empleado = self.consulta.empleado.nombrePila
        nombreapPat_empleado = self.consulta.empleado.apPat
        nombreapMat_empleado = self.consulta.empleado.apMat
        return f"{self.medicamento} - Consulta el {fecha_consulta} con {nombrePila_empleado} {nombreapPat_empleado} {nombreapMat_empleado}"

    
class MediEfecSecu(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    efectosSecundarios = models.ForeignKey('EfectosSecundarios', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

class MediContra(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    contraindicaciones = models.ForeignKey('Contraindicacion', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

class MediFormaAdmi(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    formaAdministracion = models.ForeignKey('FormaAdministracion', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

MediCare/core/templates/core/create_alergia.html
{% extends "base/tablas.html" %}

{% block title %}
  Crear Alergia
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_alergia' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/create_consulta.html
{% extends "base/tablas.html" %}

{% block title %}
  Crear consulta
{% endblock title %}

{% load static %}

{% block extra_css %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/mensajemedicamento.css' %}">
{% endblock %}

{% block content %}
  {% if messages %}
    <ul class="messages error">
      {% for message in messages %}
        <li{% if message.tags %} class="alert alert-danger"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'home:menuconsultas' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/create_empleado.html
{% extends "base/tablas.html" %}

{% block title %}
  Crear Empleado
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_empleado' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/create_medicamento.html
{% extends "base/tablas.html" %}

{% block title %}
  Crear medicamento
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_medicamento' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/delete_contraindicacion.html
{% extends "base/tablas.html" %}

{% block title %}
  Eliminar Contraindicación
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar la Contraindicación '{{ contraindicacion.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_contraindicacion' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/delete_efectos_secundarios.html
{% extends "base/tablas.html" %}

{% block title %}
  Eliminar Efecto Secundario
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar el Efecto Secundario '{{ efectos_secundarios.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_efectos_secundarios' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/detail_medi_forma_admi.html
{% extends "base/tablas.html" %}

{% block title %}
  Detalles de MediFormaAdmi
{% endblock title %}

{% block content %}
  <h2>{{ medi_forma_admi.id }}</h2>
  <p>El medicamento '{{ medi_forma_admi.medicamento.nombre }}' se administra de forma '{{ medi_forma_admi.formaAdministracion.nombre }}'.</p>
  <a href="{% url 'core:list_medi_forma_admi' %}" class="btn btn-secondary">Volver a la lista de MediFormaAdmi</a>
{% endblock content %}

MediCare/core/templates/core/detail_medicamento.html
{% extends "base/tablas.html" %}

{% block title %}
  Detalles del medicamento
{% endblock title %}

{% block content %}
  <h2>{{ medicamento.nombre }}</h2>
  <p>Esta es el medicamento '{{ medicamento.nombre }}' su descripcion es: '{{ medicamento.descripcion}}'.</p>
  <a href="{% url 'core:list_medicamento' %}" class="btn btn-secondary">Volver a la lista de medicamentos</a>
{% endblock content %}

MediCare/core/templates/core/list_consulta.html
{% extends "base/tablas.html" %}
{% load static %}
{% block title %}
  Lista de Consultas
{% endblock title %}

{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <form method="get" action="{% url 'core:list_consulta' %}" class="mb-3">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Número de Empleado">
          <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
      </form>
    </div>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Fecha</th>
        <th>Motivo</th>
        <th style="width: 260px;">Síntomas</th>  <!-- Ajustar el ancho de la columna de Síntomas -->
        <th>Empleado</th>
        <th>Médico</th>
        <th style="width: 130px;">Acciones</th>  <!-- Ajustar el ancho de la columna de Acciones -->
      </tr>
    </thead>
    <tbody>
      {% for consulta in Consultas %}
        <tr>
          <td>{{ consulta.id }}</td>
          <td>{{ consulta.fecha }}</td>
          <td>{{ consulta.motivo }}</td>
          <td>{{ consulta.sintomas }}</td>
          <td>{{ consulta.empleado.nombrePila }} {{ consulta.empleado.apPat }} {{ consulta.empleado.apMat}}</td>
          <td>{{ consulta.medico.nombrePila }} {{ consulta.medico.apPat }} {{ consulta.medico.apMat }}</td>
          <td>
            <a href="{% url 'core:detail_consulta' consulta.id %}">
              <img src="{%  static 'images/buscar.png' %}">
            </a>
            <a href="{% url 'core:update_consulta' consulta.id %}">
              <img src="{%  static 'images/editar.png' %}">
            </a>
            <a href="{% url 'core:delete_consulta' consulta.id %}">
              <img src="{%  static 'images/eliminar.png' %}">
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

MediCare/core/templates/core/list_forma_administracion.html
{% extends "base/tablas.html" %}
{% load static %}
{% block title %}
  Lista de Formas de Administración
{% endblock title %}

{% block content %}
  <a href="{% url 'core:create_forma_administracion' %}" class="btn btn-success">Crear Forma de Administración</a>
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      {% for forma_administracion in FormasAdministracion %}
        <tr>
          <td>{{ forma_administracion.id }}</td>
          <td>{{ forma_administracion.nombre }}</td>
          <td>{{ forma_administracion.descripcion }}</td>
          <td>
            <a href="{% url 'core:detail_forma_administracion' forma_administracion.id %}">
              <img src="{%  static 'images/buscar.png' %}">
            </a>
            <a href="{% url 'core:update_forma_administracion' forma_administracion.id %}">
              <img src="{%  static 'images/editar.png' %}">
            </a>
            <a href="{% url 'core:delete_forma_administracion' forma_administracion.id %}">
              <img src="{%  static 'images/eliminar.png' %}">
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

MediCare/core/templates/core/list_puesto.html
{% extends "base/tablas.html" %}
{% load static %}
{% block title %}
  Lista de Puestos
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_puesto' %}" class="btn btn-success">Crear Puesto</a>
      {% for puesto in Puestos %}
        <tr>
          <td>{{ puesto.id }}</td>
          <td>{{ puesto.nombre }}</td>
          <td>{{ puesto.descripcion }}</td>
          <td>
            <a href="{% url 'core:detail_puesto' puesto.id %}">
              <img src="{%  static 'images/buscar.png' %}">
            </a>
            <a href="{% url 'core:update_puesto' puesto.id %}">
              <img src="{%  static 'images/editar.png' %}">
            </a>
            <a href="{% url 'core:delete_puesto' puesto.id %}">
              <img src="{%  static 'images/eliminar.png' %}">
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

MediCare/core/templates/core/update_alergiaempleado.html
{% extends "base/tablas.html" %}

{% block title %}
  Actualizar AlergiaEmpleado
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'core:list_alergiaempleado' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/update_contraindicacion.html
{% extends "base/tablas.html" %}

{% block title %}
  Actualizar Contraindicación
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'core:list_contraindicacion' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

MediCare/core/templates/core/update_efectos_secundarios.html
{% extends "base/tablas.html" %}

{% block title %}
  Actualizar Efecto Secundario
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'core:list_efectos_secundarios' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}